// <auto-generated />
namespace PriceTag.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AccountDB_Creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountDB_Creation));
        
        string IMigrationMetadata.Id
        {
            get { return "201504061431330_AccountDB_Creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
