// <auto-generated />
namespace PriceTag.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class rename_Tags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_Tags));
        
        string IMigrationMetadata.Id
        {
            get { return "201504151431072_rename_Tags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
