// <auto-generated />
namespace PriceTag.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updateTag_userId_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTag_userId_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201504151514588_updateTag_userId_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
